### ISSUE TITLE
fix(e2e): repo-embedded Docker E2E broken on main — entrypoint imports an unbuilt module

### ISSUE THREAD

**Issue by moncher-dev** [hojinzs/github-symphony#861]
## Problem

`./e2e/run-e2e.sh <scenario>` fails on `main` before any scenario runs:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/app/packages/cli/dist/standalone-project.js'
  imported from /app/[eval1]
```

`e2e/seed/entrypoint.sh:46` imports it:

```sh
'import { standaloneProjectId } from "/app/packages/cli/dist/standalone-project.js"; …'
```

`packages/cli/src/standalone-project.ts` exists as source, but it is **not a tsup entry**. `packages/cli/tsup.config.ts:9-14` builds only `index`, `worker-entry`, `mcp-server` and `git-credential-helper`, so `dist/standalone-project.js` is never emitted. Confirmed absent from a clean `pnpm build` on `main`.

## Attribution

Introduced by #858 (`0944059a`):

```
$ git show 0944059a^:e2e/seed/entrypoint.sh | grep -c standalone-project.js   → 0
$ git show 0944059a:e2e/seed/entrypoint.sh  | grep -c standalone-project.js   → 1
```

Not caused by #860, which touches neither `tsup.config.ts` nor `entrypoint.sh` and merely inherits the break.

## Why CI did not catch it

`Container Smoke` was green on #858 and is green on #860, so whatever it exercises does not include this entrypoint path. `./e2e/run-standalone-project-e2e.sh` also passes, because it uses its own inline bootstrap rather than `e2e/seed/entrypoint.sh`. Only the repo-embedded runner goes through the broken import.

## Fix

Either add `standalone-project` to the tsup entry map so `dist/standalone-project.js` is emitted, or have `entrypoint.sh` derive the project id without importing an unbundled module. The first is smaller; the second removes a build-shape dependency from a shell script, which is arguably the better end state.

## Note on sequencing

#851 removes the repo-mode E2E case, which may delete the caller entirely. Worth confirming which lands first — if #851 removes `e2e/seed/entrypoint.sh`'s repo-mode bootstrap, this fix may be moot; if not, `main` stays broken until it is fixed.

## Pattern

This is the third occurrence in the removal chain of a change verified by "the new thing works" without checking the harness that consumes it — after the retired-surface callers in #849 round 1 and the unstartable `setup` output in round 3. Filed by the board steward from a real `run-e2e.sh` execution on the PR build.

**Comment by moncher-dev** [comment]
Folded into **#851**, which is dispatched now as the last step of epic #847's removal chain.

**Why it is folded rather than fixed separately.** #851 deletes the repo-mode end-to-end case and its seed entrypoint — which is the file carrying the broken import. Fixing `standalone-project.js` into the tsup entry map would repair a caller that is about to be removed, and the two changes would collide in the same files. So the resolution here is deletion, not a build-config change.

I have said that explicitly in #851's instruction, with the sequencing stated up front so the worker does not spend a round discovering it.

Two related one-line items travel with it, both in the same PR:

- `e2e/run-e2e.sh:695` still asserts `project.repositoryDir` against the removed repo-embedded state path. It was never reachable for testing, because the harness dies on **this** issue's import first.
- `e2e/run-standalone-project-e2e.sh` is missing its executable bit — `-rw-r--r--` where both sibling runners are `-rwxr-xr-x`, so direct invocation fails with permission denied and only `bash <path>` works.

**The attribution recorded here stands and is worth keeping visible even though the fix is a deletion.** The import was introduced by #858 (`git show 0944059a^:e2e/seed/entrypoint.sh | grep -c` → 0, `git show 0944059a:… | grep -c` → 1), `Container Smoke` was green across both #858 and #860 because it does not exercise that entrypoint, and `./e2e/run-standalone-project-e2e.sh` passed throughout because it bootstraps inline rather than through the seed entrypoint. That combination — a break on `main` invisible to CI and to the one E2E runner that still worked — is the reason it took a manual `run-e2e.sh` invocation to find.

Leaving this open until #851 lands so the deletion can close it, rather than closing it now on an intention.

**Comment by moncher-dev** [comment]
Resolved by **PR #862** (issue #851), merged at 12:14:47Z as `33cdf2ea`. Closing manually — that PR's body carries `Closes #851` only, so this issue was folded in by intention rather than by a closing keyword.

**Verified on `origin/main` rather than assumed:**

```
e2e/seed/entrypoint.sh   → deleted      ← the file carrying the broken import
e2e/run-e2e.sh           → deleted      ← its only caller
dist/standalone-project.js imports from shell scripts → none remaining
```

The resolution is deletion, not repair. `standalone-project` was never added to the tsup entry map, and it did not need to be: the only thing importing `/app/packages/cli/dist/standalone-project.js` was the repo-mode seed entrypoint, which epic #847's removal chain deleted. The module still exists as source and is imported normally by `project-selection.ts` and `commands/project.ts` as a source-relative ESM specifier, which requires no build entry.

**Two related items travelled in the same PR and are also resolved:** `e2e/run-e2e.sh:695`'s stale `repositoryDir` assertion went with the runner, and `e2e/run-standalone-project-e2e.sh` gained its executable bit (`mode change 100644 => 100755` — I confirmed by invoking it directly rather than through `bash`).

**Worth keeping on the record, since the fix leaves no trace of the failure.** This was a live break on `main` from 09:44Z until 12:14Z. It was introduced by #858, and it was invisible to everything that normally guards us: `Container Smoke` stayed green across #858, #860 and #862 because it never runs that entrypoint, and `run-standalone-project-e2e.sh` passed throughout because it bootstraps inline with `--entrypoint bash` rather than through the seed entrypoint. It surfaced only when I ran `./e2e/run-e2e.sh happy` by hand while verifying #860.

That combination — a break on the main branch that CI does not exercise and that the one surviving E2E runner structurally cannot see — is the reason to keep running the real harness during review rather than trusting green checks.
